#version: "2"
#
#services:
#  zookeeper:
#    image: docker.io/bitnami/zookeeper:3.8
#    ports:
#      - "2181:2181"
#    volumes:
#      - "zookeeper_data:/bitnami"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#  kafka:
#    image: docker.io/bitnami/kafka:3.4
#    ports:
#      - "9092:9092"
#    volumes:
#      - "kafka_data:/bitnami"
#    environment:
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_ENABLE_KRAFT=no
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
#    depends_on:
#      - zookeeper
#
#volumes:
#  zookeeper_data:
#    driver: local
#  kafka_data:
#    driver: local
#
#----------------------------------------------------------------------------------------
#
# 欲しいのは、このポート、でいいと思う
#
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: kafka
      port: 9092
    - name: kafka-external
      port: 9094
  selector:
    app: kafka
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - name: zookeeper-client
      port: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-zookeeper
  template:
    metadata:
      labels:
        app: kafka-zookeeper
    spec:
      containers:
        - name: zookeeper
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          image: docker.io/bitnami/zookeeper:3.8
          ports:
            - containerPort: 2181
          volumeMounts:
            - name: zookeeper-data
              mountPath: /bitnami
        - name: kafka
          image: docker.io/bitnami/kafka:3.4
          ports:
            - containerPort: 9092
            - containerPort: 9094
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami
      volumes:
        - name: zookeeper-data
          emptyDir: {}
        - name: kafka-data
          emptyDir: {}
