# https://kubernetes.io/ja/docs/tasks/access-application-cluster/connecting-frontend-backend/
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka-zookeeper
    tier: kafka
  ports:
  - protocol: "TCP"
    port: 9092
    targetPort: 9092
    name: "kafka"
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localvolume-kafka-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka-zookeeper
      tier: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-zookeeper
        tier: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
            - name: KAFKA_ENABLE_KRAFT
              value: 'no'
            - name: KAFKA_CFG_LISTENERS
              value: 'PLAINTEXT://:9092'

          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: localvolume-kafka-pvc
            readOnly: false
