# Edited. 
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    #- name: kafka
    #port: 9092
  - name: kafka-external
    port: 9094
  selector:
    app: kafka
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localvolume-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
    tier: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      tier: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
        tier: kafka
    spec:
      containers:
        - image: docker.io/bitnami/kafka:3.4
          name: kafka
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
            - name: KAFKA_CFG_BACKGROUND_THREADS
              value: "10"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,EXTERNAL://:9094"
                #- name: KAFKA_CFG_ADVERTISED_LISTENERS
                #value: "PLAINTEXT://kafka.default.svc.cluster.local:9092,EXTERNAL://192.168.86.153:9094"
          ports:
            #- containerPort: 9092
            #name: kafka
            - containerPort: 9094
              name: kafka-external
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: localvolume-pvc
            readOnly: false
