# 参考サイト
# https://kubernetes.io/ja/docs/tasks/access-application-cluster/connecting-frontend-backend/
# https://amateur-engineer-blog.com/getting-started-kafka-with-docker-compose/
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: kafka-zookeeper
    tier: zookeeper
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localvolume-zookeeper-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: kafka-zookeeper
      tier: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-zookeeper
        tier: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          ports:
            - name: zookeeper
              containerPort: 2181
          volumeMounts:
            - name: zookeeper-data
              mountPath: /bitnami
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: localvolume-zookeeper-pvc
            readOnly: false

